# Generated by Django 5.2 on 2025-04-26 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_gamingclip_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('music', 'Musique'), ('dev', 'Développement'), ('video', 'Vidéo'), ('freelance', 'Freelance'), ('art', 'Œuvre / Art'), ('service', 'Service Divers'), ('gaming', 'Gaming'), ('multiplayer', 'Jeu Multijoueur'), ('solo', 'Jeu Solo')], max_length=20),
        ),
        migrations.CreateModel(
            name='GameUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('game_file', models.FileField(upload_to='uploaded_games/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('players', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
