# Generated by Django 5.2 on 2025-04-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_service_category_gameupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameupload',
            name='game_mode',
            field=models.CharField(choices=[('solo', 'Jeu Solo'), ('multiplayer', 'Jeu Multijoueur')], default='solo', max_length=20),
        ),
    ]
