# Generated by Django 5.2 on 2025-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
