# Generated by Django 5.2 on 2025-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_customuser_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameupload',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
