# Generated by Django 5.2 on 2025-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_gameupload_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamingclip',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
    ]
